package com.fidelity.utils;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Add this annotation to methods that should be excluded
 * from EclEmma code coverage analysis during unit testing in Eclipse,
 * such as methods generated by Eclipse: hashCode(), equals(), toString(),
 * getters and setters, etc.
 * 
 * Instead of adding this annotation to each method, you can configure
 * JaCoCo exclusion filters in the pom.xml file and generate a code coverage
 * report using Maven. See https://www.baeldung.com/jacoco-report-exclude
 *  
 * @author ROI Instructor Team
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
public @interface Generated {
}
