spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iengdb
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: update  
app:
  write:
    enabled: false


