version: '3'

services:
  producer:
    image: kafka-producer
    environment:
      - BROKER=kafka1:19091
  consumer:
    image: kafka-consumer
    environment:
      - BROKER=kafka2:19092
      - MESSAGE_PROCESSING_TIME=2000